import './reset.css';
import './global.scss';

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Image from 'next/image';
import { getServerSession } from 'next-auth';
import React from 'react';

import { SessionProvider } from '@/components/providers/SessionProvider';

import waveGradientBackground from '../../public/wave-gradient-background.svg';
import styles from './Layout.module.scss';

const montserrat = Montserrat({
	subsets: ['latin-ext'],
	style: ['normal'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const bodyStyles = [styles.body, montserrat.className].join(' ');

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();

	return (
		<html lang="en">
			<body className={bodyStyles}>
				<SessionProvider session={session}>
					{children}
					<Image
						className={styles.waveGradientBackground}
						src={waveGradientBackground}
						alt="wave gradient background"
					/>
				</SessionProvider>
			</body>
		</html>
	);
}
